# Declarative IDE export only. Reuse the same explicit values as the real shader build.
# No target C++ defines, compiler command parsing or build execution is performed here.
include_guard(GLOBAL)
if(CMAKE_VERSION VERSION_LESS 3.21)
    message(FATAL_ERROR "SlangShaderVariants.cmake requires CMake 3.21 or newer")
endif()

function(_slang_ide_json_string out value)
    string(REPLACE "$<CONFIG>" "" expression_check "${value}")
    if(expression_check MATCHES "\\$<")
        message(FATAL_ERROR "Shader variant JSON supports only the $<CONFIG> generator expression; export other values explicitly")
    endif()
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${out} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(slang_ide_add_variant)
    cmake_parse_arguments(PARSE_ARGV 0 V "INHERIT_WORKSPACE"
        "ID;NAME;ROOT;ENTRY_POINT;STAGE;TARGET;PROFILE;BUILD_TARGET;CONFIGURATION" "DEFINES;UNDEFINES;INCLUDE_PATHS")
    if(V_UNPARSED_ARGUMENTS OR V_KEYWORDS_MISSING_VALUES OR NOT V_ID OR NOT V_ROOT)
        message(FATAL_ERROR "slang_ide_add_variant requires ID and ROOT, and recognized arguments with values")
    endif()
    if(NOT V_ID MATCHES "^[A-Za-z0-9_.-]+$")
        message(FATAL_ERROR "Shader variant ID must use letters, digits, underscore, dot or hyphen")
    endif()
    get_property(ids GLOBAL PROPERTY SLANG_IDE_VARIANT_IDS)
    if(V_ID IN_LIST ids)
        message(FATAL_ERROR "Duplicate Slang IDE variant ID: ${V_ID}")
    endif()
    if(NOT V_NAME)
        set(V_NAME "${V_ID}")
    endif()
    if(NOT DEFINED V_CONFIGURATION)
        set(V_CONFIGURATION "$<CONFIG>")
    endif()
    cmake_path(ABSOLUTE_PATH V_ROOT BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE OUTPUT_VARIABLE root)
    set(object "{}")
    foreach(pair IN ITEMS "id|V_ID" "name|V_NAME" "root|root" "entryPoint|V_ENTRY_POINT"
            "stage|V_STAGE" "target|V_TARGET" "profile|V_PROFILE" "buildTarget|V_BUILD_TARGET" "configuration|V_CONFIGURATION")
        string(REPLACE "|" ";" fields "${pair}")
        list(GET fields 0 key)
        list(GET fields 1 variable)
        _slang_ide_json_string(encoded "${${variable}}")
        string(JSON object SET "${object}" "${key}" "${encoded}")
    endforeach()
    if(V_INHERIT_WORKSPACE)
        string(JSON object SET "${object}" inheritWorkspace true)
    else()
        string(JSON object SET "${object}" inheritWorkspace false)
    endif()
    set(defines "{}")
    set(names "")
    foreach(definition IN LISTS V_DEFINES)
        string(FIND "${definition}" "=" position)
        if(position EQUAL -1)
            set(name "${definition}")
            set(value "") # Slang's -DNAME means an empty replacement, not 1.
        else()
            string(SUBSTRING "${definition}" 0 ${position} name)
            math(EXPR position "${position} + 1")
            string(SUBSTRING "${definition}" ${position} -1 value)
        endif()
        if(NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$" OR name IN_LIST names)
            message(FATAL_ERROR "Invalid or duplicate shader macro: ${name}")
        endif()
        list(APPEND names "${name}")
        _slang_ide_json_string(encoded "${value}")
        string(JSON defines SET "${defines}" "${name}" "${encoded}")
    endforeach()
    string(JSON object SET "${object}" defines "${defines}")
    set(undefines "[]")
    set(index 0)
    foreach(name IN LISTS V_UNDEFINES)
        if(NOT name MATCHES "^[A-Za-z_][A-Za-z0-9_]*$" OR name IN_LIST names)
            message(FATAL_ERROR "Conflicting or invalid shader undefine: ${name}")
        endif()
        list(APPEND names "${name}")
        _slang_ide_json_string(encoded "${name}")
        string(JSON undefines SET "${undefines}" ${index} "${encoded}")
        math(EXPR index "${index} + 1")
    endforeach()
    string(JSON object SET "${object}" undefines "${undefines}")
    set(paths "[]")
    set(index 0)
    foreach(path IN LISTS V_INCLUDE_PATHS)
        cmake_path(ABSOLUTE_PATH path BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE OUTPUT_VARIABLE absolute)
        _slang_ide_json_string(encoded "${absolute}")
        string(JSON paths SET "${paths}" ${index} "${encoded}")
        math(EXPR index "${index} + 1")
    endforeach()
    string(JSON object SET "${object}" includePaths "${paths}")
    set_property(GLOBAL APPEND PROPERTY SLANG_IDE_VARIANT_IDS "${V_ID}")
    set_property(GLOBAL PROPERTY "SLANG_IDE_VARIANT_${V_ID}" "${object}")
endfunction()

function(slang_ide_export_variants)
    cmake_parse_arguments(PARSE_ARGV 0 E "" "OUTPUT" "")
    if(NOT E_OUTPUT OR E_UNPARSED_ARGUMENTS OR E_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "slang_ide_export_variants requires an explicit OUTPUT path")
    endif()
    get_property(ids GLOBAL PROPERTY SLANG_IDE_VARIANT_IDS)
    set(contexts "[]")
    set(index 0)
    foreach(id IN LISTS ids)
        get_property(object GLOBAL PROPERTY "SLANG_IDE_VARIANT_${id}")
        string(JSON contexts SET "${contexts}" ${index} "${object}")
        math(EXPR index "${index} + 1")
    endforeach()
    set(document "{\"version\":1}")
    string(JSON document SET "${document}" contexts "${contexts}")
    # Use $<CONFIG> in OUTPUT for multi-config builds; configure/generate never compiles shaders.
    file(GENERATE OUTPUT "${E_OUTPUT}" CONTENT "${document}\n")
endfunction()
